2020-04-28 11:54:35,734 p=7766 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 11:54:35,735 p=7766 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test

2020-04-28 11:54:59,849 p=7786 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 11:54:59,850 p=7786 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test

2020-04-28 16:26:16,939 p=17448 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:26:16,940 p=17448 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test
2020-04-28 16:32:14,016 p=17878 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:32:14,017 p=17878 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test

2020-04-28 16:32:47,388 p=17913 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:32:47,388 p=17913 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test

2020-04-28 16:37:42,887 p=18510 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:37:42,888 p=18510 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test

2020-04-28 16:40:50,132 p=18622 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:40:50,132 p=18622 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test

2020-04-28 16:48:39,656 p=18976 u=root |  ERROR! Extraneous options or arguments
2020-04-28 16:49:14,332 p=18992 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:49:14,332 p=18992 u=root |   [WARNING]: Could not match supplied host pattern, ignoring: test

2020-04-28 16:53:26,684 p=19127 u=root |   [WARNING]:  * Failed to parse /ansible/hosts with yaml plugin: Syntax Error while loading YAML.   did not find expected <document start>  The error appears to be in '/ansible/hosts': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:  [web] 3.15.215.191 ^ here

2020-04-28 16:53:26,684 p=19127 u=root |   [WARNING]:  * Failed to parse /ansible/hosts with ini plugin: /ansible/hosts:10: Section [multi:test_all] has unknown type: test_all

2020-04-28 16:53:26,685 p=19127 u=root |   [WARNING]: Unable to parse /ansible/hosts as an inventory source

2020-04-28 16:53:26,685 p=19127 u=root |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-04-28 16:53:26,686 p=19127 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:53:39,402 p=19127 u=root |  3.21.170.235 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '3.21.170.235' (ECDSA) to the list of known hosts.\r\nroot@3.21.170.235: Permission denied (publickey).",
    "unreachable": true
}
2020-04-28 16:58:48,721 p=19377 u=root |   [WARNING]:  * Failed to parse /ansible/hosts with yaml plugin: Syntax Error while loading YAML.   did not find expected <document start>  The error appears to be in '/ansible/hosts': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:  [web] 3.15.215.191 ^ here

2020-04-28 16:58:48,721 p=19377 u=root |   [WARNING]:  * Failed to parse /ansible/hosts with ini plugin: /ansible/hosts:10: Section [multi:test_all] has unknown type: test_all

2020-04-28 16:58:48,721 p=19377 u=root |   [WARNING]: Unable to parse /ansible/hosts as an inventory source

2020-04-28 16:58:48,721 p=19377 u=root |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-04-28 16:58:48,722 p=19377 u=root |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-04-28 16:59:22,745 p=19377 u=root |   [WARNING]: Unhandled error in Python interpreter discovery for host 3.21.170.235: unexpected output from Python interpreter discovery

2020-04-28 16:59:24,089 p=19377 u=root |   [WARNING]: sftp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 16:59:25,419 p=19377 u=root |   [WARNING]: scp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 16:59:56,369 p=19377 u=root |   [WARNING]: Platform unknown on host 3.21.170.235 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information.

2020-04-28 16:59:56,369 p=19377 u=root |  3.21.170.235 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 3.21.170.235 closed.\r\n",
    "module_stdout": "Please login as the user \"ubuntu\" rather than the user \"root\".\r\n\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0
}
2020-04-28 17:07:50,527 p=19815 u=root |   [WARNING]: Found both group and host with same name: test

2020-04-28 17:07:50,527 p=19815 u=root |   [WARNING]: Found both group and host with same name: web

2020-04-28 17:07:50,527 p=19815 u=root |   [WARNING]: Found both group and host with same name: db

2020-04-28 17:07:50,765 p=19815 u=root |  test | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname test: Temporary failure in name resolution",
    "unreachable": true
}
2020-04-28 17:09:14,236 p=19844 u=root |   [WARNING]: Unhandled error in Python interpreter discovery for host 3.21.170.235: unexpected output from Python interpreter discovery

2020-04-28 17:09:15,554 p=19844 u=root |   [WARNING]: sftp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:09:16,873 p=19844 u=root |   [WARNING]: scp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:09:47,830 p=19844 u=root |   [WARNING]: Platform unknown on host 3.21.170.235 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information.

2020-04-28 17:09:47,831 p=19844 u=root |  3.21.170.235 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 3.21.170.235 closed.\r\n",
    "module_stdout": "Please login as the user \"ubuntu\" rather than the user \"root\".\r\n\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0
}
2020-04-28 17:15:16,856 p=20117 u=root |   [WARNING]: Unhandled error in Python interpreter discovery for host 3.21.170.235: unexpected output from Python interpreter discovery

2020-04-28 17:15:18,171 p=20117 u=root |   [WARNING]: sftp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:15:19,485 p=20117 u=root |   [WARNING]: scp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:15:50,429 p=20117 u=root |   [WARNING]: Platform unknown on host 3.21.170.235 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information.

2020-04-28 17:15:50,429 p=20117 u=root |  3.21.170.235 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 3.21.170.235 closed.\r\n",
    "module_stdout": "Please login as the user \"ubuntu\" rather than the user \"root\".\r\n\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0
}
2020-04-28 17:18:12,920 p=20220 u=root |   [WARNING]: Unhandled error in Python interpreter discovery for host 3.21.170.235: unexpected output from Python interpreter discovery

2020-04-28 17:18:14,237 p=20220 u=root |   [WARNING]: sftp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:18:15,553 p=20220 u=root |   [WARNING]: scp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:18:46,507 p=20220 u=root |   [WARNING]: Platform unknown on host 3.21.170.235 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information.

2020-04-28 17:18:46,507 p=20220 u=root |  3.21.170.235 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 3.21.170.235 closed.\r\n",
    "module_stdout": "Please login as the user \"ubuntu\" rather than the user \"root\".\r\n\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0
}
2020-04-28 17:19:28,386 p=20288 u=root |  127.0.0.1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 22: Connection refused",
    "unreachable": true
}
2020-04-28 17:19:59,445 p=20288 u=root |   [WARNING]: Unhandled error in Python interpreter discovery for host 3.21.170.235: unexpected output from Python interpreter discovery

2020-04-28 17:20:00,766 p=20288 u=root |   [WARNING]: sftp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:20:02,084 p=20288 u=root |   [WARNING]: scp transfer mechanism failed on [3.21.170.235]. Use ANSIBLE_DEBUG=1 to see detailed information

2020-04-28 17:20:33,041 p=20288 u=root |   [WARNING]: Platform unknown on host 3.21.170.235 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information.

2020-04-28 17:20:33,041 p=20288 u=root |  3.21.170.235 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 3.21.170.235 closed.\r\n",
    "module_stdout": "Please login as the user \"ubuntu\" rather than the user \"root\".\r\n\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0
}
2020-04-29 02:44:09,020 p=5535 u=root |  ERROR! Missing target hosts
2020-04-29 02:44:23,662 p=5563 u=root |  ERROR! No argument passed to command module
2020-04-29 02:44:57,868 p=5573 u=root |  3.21.170.235 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2020-04-29 02:46:00,682 p=5620 u=root |  3.21.170.235 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2020-04-29 02:46:23,582 p=5620 u=root |  3.16.158.104 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Host key verification failed.",
    "unreachable": true
}
2020-04-29 02:46:24,382 p=5620 u=root |  3.15.215.191 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Host key verification failed.",
    "unreachable": true
}
2020-04-29 02:46:44,819 p=5661 u=root |  3.15.215.191 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2020-04-29 02:47:00,741 p=5688 u=root |  3.16.158.104 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2020-04-29 02:47:24,585 p=5734 u=root |  3.16.158.104 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2020-04-29 02:47:24,672 p=5734 u=root |  3.15.215.191 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2020-04-29 02:47:26,140 p=5734 u=root |  3.21.170.235 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
